---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: kubeadm-ami
spec:
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: <cluster-name>
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: <cluster-name>
  amiFamily: custom
  amiSelectorTerms:
    - id: ami-02225abf02fa7ee82
  role: EBS-drivers
  userData: |
    #!/bin/bash
    # fetch AWS metadata
    TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
    INST_ID=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/instance-id)
    AZ=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/placement/availability-zone)
    NODE_NAME=$(hostname -s)

    # Generate the kubeadm join config
    cat <<EOF > /home/ubuntu/kubeadm-join.conf
    apiVersion: kubeadm.k8s.io/v1beta4
    kind: JoinConfiguration
    discovery: 
      bootstrapToken:
        apiServerEndpoint: "<control-plane-endpoint>:6443"
        token: "<bootstrap-token>"
        unsafeSkipCAVerification: true
        caCertHashes: 
          - "<ca-cert-hash>"
    nodeRegistration:
      name: ${NODE_NAME}
      criSocket: "unix:///var/run/containerd/containerd.sock"
      imagePullPolicy: IfNotPresent
      imagePullSerial: true
      taint: null
      kubeletExtraArgs:
        - name: provider-id
          value: aws:///${AZ}/${INST_ID}
        - name: node-labels
          value: "app=tradein"
    EOF
    # Run the join command
    sudo kubeadm join --config /home/ubuntu/kubeadm-join.conf >> /var/log/kubeadm-join.log 2>&1

---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: tradein-worker
spec:
  template:
    metadata:
      labels:
        app: tradein
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: kubeadm-ami
      requirements:
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["c7i-flex", "m7i-flex"]
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values: ["2", "4"]
        - key: karpenter.k8s.aws/instance-memory
          operator: In
          values: ["4", "8"]
  limits:
    cpu: "1000"
    memory: "1000Gi"
    nodes: "10"
