---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-image-updater-secrets
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: tradein-aws-store   
    kind: ClusterSecretStore
  target:
    name: aws-ecr-creds
    creationPolicy: Owner
  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: argocd/in/github-sso    
        property: aws_access_key_id
    - secretKey: aws_secret_access_key
      remoteRef:
        key: argocd/in/github-sso
        property: aws_secret_access_key
    - secretKey: aws_region
      remoteRef:
        key: argocd/in/github-sso
        property: aws_region
    - secretKey: sshPrivateKey  
      remoteRef:
        key: argocd/in/github-sso
        property: sshPrivateKey
