---
- name: Install HAProxy LB
  ansible.builtin.apt:
    name: haproxy
    state: present

- name: Ensure /etc/haproxy directory exists
  ansible.builtin.file:
    path: /etc/haproxy
    state: directory
    mode: "0755"

- name: Configure HAProxy
  ansible.builtin.copy:
    dest: /etc/haproxy/haproxy.cfg
    content: |
      global 
        log /dev/log local0
        log /dev/log local1 notice
        daemon

      defaults
        log global
        mode tcp
        option tcplog
        timeout connect 5000ms
        timeout client 50000ms
        timeout server 50000ms

      frontend k8s-frontend
        bind *:6443
        mode tcp
        option tcplog
        default_backend k8s-backend

      backend k8s-backend
        mode tcp
        option tcp-check
        balance roundrobin
        server k8smaster1 {{ k8smaster1_pvt_ip }}:6443 check fall 3 rise 2
        server k8smaster2 {{ k8smaster2_pvt_ip }}:6443 check fall 3 rise 2

      listen stats
        bind *:8404
        mode http
        timeout connect 10s
        timeout client 10s
        timeout server 10s
        stats enable
        stats uri /stats
        stats refresh 10s
        stats auth admin:{{ haproxy_password }}

- name: Ensure HAProxy service is enabled and started
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true

- name: Restart HAProxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
