---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: tradein-aws-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-tradein
  namespace: tradein
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: tradein-aws-store
    kind: ClusterSecretStore
  target:
    name: tradein-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: trade/in/prod
