---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarqube
  namespace: base
spec:
  serviceName: "sonarqube"
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      nodeSelector:
        node: base
      initContainers:
        - name: busybox
          image: busybox
          command:
            - sh
            - -c
            - |
              chown -R 1000:1000 /opt/sonarqube/data
              chown -R 1000:1000 /opt/sonarqube/extensions/plugins
              sysctl -w vm.max_map_count=262144
              wget -O /opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/1.21.0/sonarqube-community-branch-plugin-1.21.0.jar
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /opt/sonarqube/data
            - name: plugins
              mountPath: /opt/sonarqube/extensions/plugins

      securityContext:
        fsGroup: 1000
      containers:
        - name: sonarqube
          image: sonarqube:lts
          env:
          securityContext:
            runAsUser: 1000
          ports:
            - containerPort: 9000
          resources:
            limits:
              memory: "4G"
              cpu: "2.0"
            requests:
              memory: "1.5G"
              cpu: "1.0"
          volumeMounts:
            - name: data
              mountPath: /opt/sonarqube/data
            - name: plugins
              mountPath: /opt/sonarqube/extensions/plugins
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ebs
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: plugins
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ebs
        resources:
          requests:
            storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: base
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - port: 9000
      targetPort: 9000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarqube
  namespace: base
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/group.name: tradein-alb
spec:
  ingressClassName: alb
  tls:
    - hosts:
        - sonar.rogaikwad.online
      secretName: encrypt-tls
  rules:
    - host: sonar.rogaikwad.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarqube
                port:
                  number: 9000
