name: Tradein DevSecOps pipeline
on: [push, workflow_dispatch]
jobs:
  clone: 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout tradein repo
        uses: actions/checkout@v6
        with: 
          repository: rohitG7496/tradeIn
          ref: main
      - name: setup node js 
        uses: actions/setup-node@v4
        with: 
          node-version: 16
      - name: install dependencies
        run: |
          cd Frontend
          npm install --legacy-peer-deps
      - name: snyk security scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
        with: 
          command: monitor
          args: --file=Frontend/package.json --project-name="TradeIn-Frontend-GHA"